# Generated by Django 4.2.25 on 2025-10-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_category_remove_lesson_visibility_lesson_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='mastered',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='lessons.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.flashcardset'),
        ),
    ]
